[2025-09-04T10:00:01.992+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quantum_daily_stock_analysis.check_market_status manual__2025-09-04T10:00:00+00:00 [queued]>
[2025-09-04T10:00:01.996+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quantum_daily_stock_analysis.check_market_status manual__2025-09-04T10:00:00+00:00 [queued]>
[2025-09-04T10:00:01.996+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 3
[2025-09-04T10:00:02.003+0000] {taskinstance.py:2214} INFO - Executing <Task(PythonOperator): check_market_status> on 2025-09-04 10:00:00+00:00
[2025-09-04T10:00:02.006+0000] {standard_task_runner.py:60} INFO - Started process 378 to run task
[2025-09-04T10:00:02.008+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'quantum_daily_stock_analysis', 'check_market_status', 'manual__2025-09-04T10:00:00+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/quantum_stock_analysis_dag.py', '--cfg-path', '/tmp/tmpkl_7moze']
[2025-09-04T10:00:02.010+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask check_market_status
[2025-09-04T10:00:02.053+0000] {task_command.py:423} INFO - Running <TaskInstance: quantum_daily_stock_analysis.check_market_status manual__2025-09-04T10:00:00+00:00 [running]> on host 0adc8544e250
[2025-09-04T10:00:02.116+0000] {taskinstance.py:2510} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='quantum-trading' AIRFLOW_CTX_DAG_ID='quantum_daily_stock_analysis' AIRFLOW_CTX_TASK_ID='check_market_status' AIRFLOW_CTX_EXECUTION_DATE='2025-09-04T10:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-09-04T10:00:00+00:00'
[2025-09-04T10:00:02.117+0000] {taskinstance.py:2728} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 439, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quantum_stock_analysis_dag.py", line 48, in check_market_status
    import holidays
ModuleNotFoundError: No module named 'holidays'
[2025-09-04T10:00:02.124+0000] {taskinstance.py:1149} INFO - Marking task as UP_FOR_RETRY. dag_id=quantum_daily_stock_analysis, task_id=check_market_status, execution_date=20250904T100000, start_date=20250904T100001, end_date=20250904T100002
[2025-09-04T10:00:02.132+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 3 for task check_market_status (No module named 'holidays'; 378)
[2025-09-04T10:00:02.149+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-09-04T10:00:02.166+0000] {taskinstance.py:3309} INFO - 0 downstream tasks scheduled from follow-on schedule check
